import { useEffect, useState } from 'react'
import { storesApi, type Store, type StoreQuery } from '../../api/stores.api'
import { RatingStars } from '../../components/RatingStars'

export function StoresList() {
  const [stores, setStores] = useState<Store[]>([]); const [meta, setMeta] = useState({ page: 1, limit: 10, total: 0, totalPages: 0 }); const [query, setQuery] = useState<StoreQuery>({ page: 1, limit: 10, sortBy: 'averageRating', order: 'DESC' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { storesApi.list(query).then((response) => { setStores(response.data.data.data); setMeta(response.data.data.meta) }).catch(() => setError('Unable to load stores.')).finally(() => setLoading(false)) }, [query])
  const update = (key: keyof StoreQuery, value: string) => setQuery((current) => ({ ...current, [key]: value || undefined, page: 1 }))
  const rate = async (store: Store, rating: number) => { setError(''); try { if (store.userRating === null) await storesApi.submitRating(store.id, rating); else await storesApi.updateRating(store.id, rating); setStores((current) => current.map((item) => item.id === store.id ? { ...item, userRating: rating, averageRating: item.userRating === null ? Number(((item.averageRating + rating) / 2).toFixed(2)) : item.averageRating } : item)) } catch { setError('Unable to save your rating.') } }
  return <section className="user-page"><p className="eyebrow">Customer directory</p><h1>Find a store. Leave a signal.</h1><div className="filter-bar"><input placeholder="Search store name" value={query.name ?? ''} onChange={(event) => update('name', event.target.value)} /><input placeholder="Search address" value={query.address ?? ''} onChange={(event) => update('address', event.target.value)} /><select value={query.sortBy} onChange={(event) => update('sortBy', event.target.value)}><option value="averageRating">Sort by rating</option><option value="name">Sort by name</option><option value="address">Sort by address</option><option value="createdAt">Sort newest</option></select><select value={query.order} onChange={(event) => update('order', event.target.value)}><option value="DESC">Descending</option><option value="ASC">Ascending</option></select></div>{error && <p className="form-error">{error}</p>}{loading ? <p className="muted">Loading stores...</p> : <div className="store-grid">{stores.map((store) => <article className="store-card" key={store.id}><div><p className="store-label">Store</p><h2>{store.name}</h2><p>{store.address}</p><a href={`mailto:${store.email}`}>{store.email}</a></div><div className="store-rating"><div><span className="rating-number">{store.averageRating.toFixed(1)}</span><span className="muted"> overall</span></div><RatingStars value={store.averageRating} label={`${store.name} overall rating`} /><div className="your-rating"><span>Your rating</span><RatingStars value={store.userRating} onChange={(rating) => rate(store, rating)} label={`${store.name} your rating`} /></div></div></article>)}</div>}{!loading && stores.length === 0 && <p className="muted">No stores match your search.</p>}<div className="pagination"><button disabled={meta.page <= 1} onClick={() => setQuery((current) => ({ ...current, page: meta.page - 1 }))}>Previous</button><span>Page {meta.page} of {Math.max(meta.totalPages, 1)}</span><button disabled={meta.page >= meta.totalPages} onClick={() => setQuery((current) => ({ ...current, page: meta.page + 1 }))}>Next</button></div></section>
}
