import { useEffect, useState } from 'react'
import { adminApi, type AdminQuery, type AdminStore, type AdminUser } from '../../api/admin.api'
import { DataTable } from '../../components/DataTable'
import { Pagination } from './UsersList'

export function StoresList() {
  const [stores, setStores] = useState<AdminStore[]>([]); const [owners, setOwners] = useState<AdminUser[]>([]); const [meta, setMeta] = useState({ page: 1, limit: 10, total: 0, totalPages: 0 }); const [query, setQuery] = useState<AdminQuery>({ page: 1, limit: 10, order: 'ASC', sortBy: 'name' }); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('')
  const load = () => adminApi.stores(query).then((response) => { setStores(response.data.data.data); setMeta(response.data.data.meta) }).catch(() => setError('Unable to load stores.'))
  useEffect(() => { adminApi.stores(query).then((response) => { setStores(response.data.data.data); setMeta(response.data.data.meta) }).catch(() => setError('Unable to load stores.')); adminApi.users({ role: 'STORE_OWNER', page: 1, limit: 100 }).then((response) => setOwners(response.data.data.data)).catch(() => undefined) }, [query])
  const update = (key: keyof AdminQuery, value: string) => setQuery((current) => ({ ...current, [key]: value || undefined, page: 1 }))
  return <section className="admin-page"><div className="page-heading"><div><p className="eyebrow">Directory</p><h1>Stores</h1></div><button className="primary-button" onClick={() => setShowForm(!showForm)}>{showForm ? 'Close form' : 'Add store'}</button></div>{showForm && <CreateStoreForm owners={owners} onCreated={() => { setShowForm(false); load() }} />}{error && <p className="form-error">{error}</p>}<div className="filter-bar"><input placeholder="Search name" onChange={(event) => update('name', event.target.value)} /><input placeholder="Search address" onChange={(event) => update('address', event.target.value)} /><select defaultValue="name" onChange={(event) => update('sortBy', event.target.value)}><option value="name">Sort name</option><option value="email">Sort email</option><option value="address">Sort address</option><option value="createdAt">Sort newest</option></select></div><DataTable rows={stores} columns={[{ key: 'name', label: 'Name', render: (store) => store.name }, { key: 'email', label: 'Email', render: (store) => store.email }, { key: 'address', label: 'Address', render: (store) => store.address }, { key: 'owner', label: 'Owner', render: (store) => store.owner?.name ?? 'Unassigned' }]} /><Pagination meta={meta} setPage={(page) => setQuery((current) => ({ ...current, page }))} /></section>
}

function CreateStoreForm({ owners, onCreated }: { owners: AdminUser[]; onCreated: () => void }) { const [form, setForm] = useState({ name: '', email: '', address: '', ownerId: owners[0]?.id ?? 0 }); const [error, setError] = useState(''); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await adminApi.createStore({ ...form, ownerId: Number(form.ownerId) }); onCreated() } catch (requestError: any) { setError(requestError.response?.data?.message?.join?.(', ') ?? 'Unable to create store.') } }; return <form className="inline-form" onSubmit={submit}><input required placeholder="Store name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input required type="email" placeholder="Store email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input required placeholder="Address" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /><select required value={form.ownerId} onChange={(e) => setForm({ ...form, ownerId: Number(e.target.value) })}><option value={0} disabled>Select owner</option>{owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name} Â· {owner.email}</option>)}</select><button className="primary-button">Create store</button>{error && <p className="form-error">{error}</p>}</form> }
