import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { adminApi, type AdminQuery, type AdminUser } from '../../api/admin.api'
import type { Role } from '../../types'
import { DataTable } from '../../components/DataTable'

export function UsersList() {
  const [users, setUsers] = useState<AdminUser[]>([]); const [meta, setMeta] = useState({ page: 1, limit: 10, total: 0, totalPages: 0 }); const [query, setQuery] = useState<AdminQuery>({ page: 1, limit: 10, order: 'ASC', sortBy: 'name' }); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('')
  const load = () => adminApi.users(query).then((response) => { setUsers(response.data.data.data); setMeta(response.data.data.meta) }).catch(() => setError('Unable to load users.'))
  useEffect(() => { adminApi.users(query).then((response) => { setUsers(response.data.data.data); setMeta(response.data.data.meta) }).catch(() => setError('Unable to load users.')) }, [query])
  const update = (key: keyof AdminQuery, value: string) => setQuery((current) => ({ ...current, [key]: value || undefined, page: 1 }))
  return <section className="admin-page"><div className="page-heading"><div><p className="eyebrow">Directory</p><h1>Users</h1></div><button className="primary-button" onClick={() => setShowForm(!showForm)}>{showForm ? 'Close form' : 'Add user'}</button></div>{showForm && <CreateUserForm onCreated={() => { setShowForm(false); load() }} />}{error && <p className="form-error">{error}</p>}<div className="filter-bar"><input placeholder="Search name" onChange={(event) => update('name', event.target.value)} /><input placeholder="Search email" onChange={(event) => update('email', event.target.value)} /><select defaultValue="" onChange={(event) => update('role', event.target.value as Role)}><option value="">All roles</option><option value="ADMIN">Admin</option><option value="NORMAL_USER">Normal user</option><option value="STORE_OWNER">Store owner</option></select><select defaultValue="name" onChange={(event) => update('sortBy', event.target.value)}><option value="name">Sort name</option><option value="email">Sort email</option><option value="role">Sort role</option><option value="createdAt">Sort newest</option></select></div><DataTable rows={users} columns={[{ key: 'name', label: 'Name', render: (user) => <Link to={`/app/admin/users/${user.id}`}>{user.name}</Link> }, { key: 'email', label: 'Email', render: (user) => user.email }, { key: 'role', label: 'Role', render: (user) => <span className="tag">{user.role.replace('_', ' ')}</span> }, { key: 'address', label: 'Address', render: (user) => user.address }]} /><Pagination meta={meta} setPage={(page) => setQuery((current) => ({ ...current, page }))} /></section>
}

function CreateUserForm({ onCreated }: { onCreated: () => void }) { const [form, setForm] = useState({ name: '', email: '', password: '', address: '', role: 'NORMAL_USER' as Role }); const [error, setError] = useState(''); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await adminApi.createUser(form); onCreated() } catch (requestError: any) { setError(requestError.response?.data?.message?.join?.(', ') ?? 'Unable to create user.') } }; return <form className="inline-form" onSubmit={submit}><input required placeholder="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input required type="password" placeholder="Password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><input required placeholder="Address" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as Role })}><option value="NORMAL_USER">Normal user</option><option value="STORE_OWNER">Store owner</option><option value="ADMIN">Admin</option></select><button className="primary-button">Create user</button>{error && <p className="form-error">{error}</p>}</form> }
function Pagination({ meta, setPage }: { meta: { page: number; totalPages: number }; setPage: (page: number) => void }) { return <div className="pagination"><button disabled={meta.page <= 1} onClick={() => setPage(meta.page - 1)}>Previous</button><span>Page {meta.page} of {Math.max(meta.totalPages, 1)}</span><button disabled={meta.page >= meta.totalPages} onClick={() => setPage(meta.page + 1)}>Next</button></div> }
export { Pagination }
